### ISSUE TITLE
Failure to compile with gcc@6.3.0

### ISSUE THREAD

**Issue by hartzell** [agordon/libgtextutils#10]
I've been building fastx-toolkit (and libgtextutil as a dependency) via the [spack recipe](https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/libgtextutils/package.py) with gcc@5.4.0 for some time.

Today I tried building with gcc@6.4.0.

The build crashed.

Here is the error.

```
text_line_reader.cpp: In member function ‘bool TextLineReader::next_line()’:
text_line_reader.cpp:47:9: error: cannot convert ‘std::istream {aka std::basic_istream<char>}’ to ‘bool’ in return
  return input_stream ;
         ^~~~~~~~~~~~
make[3]: *** [text_line_reader.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
```

I can share the complete build output in a private channel if it would be useful.

**Comment by brobr** [comment]
also with gcc7; same error

**Comment by hartzell** [comment]
Yeah, the change is this:

> The default mode for C++ is now -std=gnu++14 instead of -std=gnu++98.
> 
> [[gcc changes doc]](https://gcc.gnu.org/gcc-6/changes.html)

**Comment by brobr** [comment]
Hi,

Thanks for sorting this out. The libgtextutils program compiles now at my end with gcc 7.1 but only AFTER replacing the original text_readliner.cpp of libgtextutils-0.7 (released 2014) with the updated text_readliner.cpp. Then, this version (libgtextutils-0.7.1) compiles. The "master", however, when downloaded (https://github.com/agordon/libgtextutils/archive/master.zip) did not compile by lack of /config, /INSTALL  and other stuff that is in libgtextutils-0.7. 

Maybe something went wrong creating the master?

CHeers,

Rob

**Comment by hartzell** [comment]
The master branch contains the *maintainer's* source for the library; it's not prepared for general consumption.

It uses autotools, when @agordon creates a release he runs bits of the autotools family to create a  tree that's suitable for end-users, which he attaches to each of the releases on the releases page.

I'm not sure what his invocation is (don't see it docmented).  You could try `autoreconf -if` and see if it gets you what you need.
